### ISSUE TITLE
Typo of order

### ISSUE THREAD

**Issue by chanchancl** [StefanGreve/htw-ag#7]
In the section Installation.GeneralSetup

> Virtual environments can be activated in two different ways, depending on the operating system you are using.
> \# Windows
> source venv/bin/activate
> \# Linux
> venv/Scripts/activate.ps1

Is that wrong order for windows and linux?
should be:
\# Windows
venv/Scripts/activate.ps1
\# Linux
source venv/bin/activate

**Comment by StefanGreve** [comment]
Yes, you are right. I'll fix this in my next commit to this repo (*￣∇￣)ノ
